import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'ta';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Header
    'site.title': 'Tamil Nadu Blood Foundation',
    'site.subtitle': 'Saving Lives Together',
    'emergency.hotline': 'Emergency: 1962',
    
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.contact': 'Contact Us',
    'nav.facilities': 'Facilities',
    'nav.join': 'Join as Donor',
    'nav.emergency': 'Emergency Requests',
    
    // Home Page
    'hero.title': 'Save Lives Through Blood Donation',
    'hero.subtitle': 'Connecting generous donors with those in urgent need across all 38 districts of Tamil Nadu',
    'stats.donors': 'Active Donors',
    'stats.districts': 'Districts Covered',
    'stats.service': 'Emergency Service',
    'cta.donate': 'Become a Donor',
    'cta.emergency': 'Emergency Request',
    
    // Emergency Section
    'emergency.urgent': 'Urgent Blood Requests',
    'emergency.needed': 'needed for',
    'emergency.contact': 'Contact:',
    
    // Search Section
    'search.title': 'Find Blood Donors',
    'search.subtitle': 'Search by district and blood group to find available donors near you',
    'search.district': 'Search District',
    'search.district.placeholder': 'Enter district name...',
    'search.bloodgroup': 'Blood Group (Optional)',
    'search.bloodgroup.all': 'All Blood Groups',
    'search.button': 'Search Donors',
    
    // Districts
    'districts.title': 'Browse by District',
    'districts.subtitle': 'Select your district to find blood donors in your area',
    'districts.find': 'Find Donors',
    'districts.none': 'No districts found matching',
    
    // Blood Group Selection
    'bloodgroup.title': 'Blood Donors in',
    'bloodgroup.subtitle': 'Select the blood group you need',
    'bloodgroup.back': 'Back to Districts',
    'bloodgroup.type': 'Blood Type',
    'bloodgroup.compatibility': 'Blood Compatibility',
    'bloodgroup.universal.donor': 'Universal Donor:',
    'bloodgroup.universal.recipient': 'Universal Recipient:',
    'bloodgroup.verify': 'Remember: Always verify compatibility with medical professionals before transfusion.',
    'bloodgroup.guidelines': 'Donation Guidelines',
    'bloodgroup.gap': 'Minimum 3-month gap between donations',
    'bloodgroup.age': 'Age: 18-65 years',
    'bloodgroup.weight': 'Weight: Minimum 50kg',
    'bloodgroup.health': 'Good health condition required',
    
    // Donor List
    'donorlist.title': 'Donors in',
    'donorlist.found': 'donors found',
    'donorlist.back': 'Back to Blood Groups',
    'donorlist.name': 'Name',
    'donorlist.age': 'Age',
    'donorlist.bloodgroup': 'Blood Group',
    'donorlist.lastdonated': 'Last Donated',
    'donorlist.status': 'Status',
    'donorlist.contact': 'Contact',
    'donorlist.years': 'years',
    'donorlist.available': 'Available',
    'donorlist.notavailable': 'Not Available',
    'donorlist.recent': 'Recently donated',
    'donorlist.call': 'Call',
    'donorlist.whatsapp': 'WhatsApp',
    'donorlist.none': 'No Donors Found',
    'donorlist.none.desc': 'We couldn\'t find any',
    'donorlist.none.desc2': 'donors in',
    'donorlist.none.desc3': 'at the moment.',
    'donorlist.register': 'Register as Donor',
    'donorlist.emergency': 'Post Emergency Request',
    
    // About Page
    'about.title': 'About Tamil Nadu Blood Foundation',
    'about.subtitle': 'Bridging the gap between generous blood donors and those in urgent need across Tamil Nadu',
    'about.mission': 'Our Mission',
    'about.mission.text': 'To create a robust network connecting blood donors with patients in need across all 38 districts of Tamil Nadu. We strive to ensure that no life is lost due to unavailability of blood by maintaining an efficient, accessible, and reliable blood donation system.',
    'about.vision': 'Our Vision',
    'about.vision.text': 'To become Tamil Nadu\'s most trusted platform for blood donation, where every citizen has easy access to safe blood when needed, and every willing donor can contribute to saving lives in their community and beyond.',
    'about.what': 'What We Do',
    'about.what.subtitle': 'Our comprehensive platform connects donors with recipients and provides essential services',
    'about.donor.reg': 'Donor Registration',
    'about.donor.reg.text': 'Easy registration process for willing blood donors across all districts of Tamil Nadu',
    'about.emergency.resp': 'Emergency Response',
    'about.emergency.resp.text': '24/7 emergency blood request system connecting patients with available donors instantly',
    'about.district.cov': 'District Coverage',
    'about.district.cov.text': 'Complete coverage of all 38 Tamil Nadu districts with localized donor networks',
    'about.impact': 'Our Impact',
    'about.impact.subtitle': 'Making a difference across Tamil Nadu',
    'about.impact.donors': 'Registered Donors',
    'about.impact.districts': 'Districts Covered',
    'about.impact.lives': 'Lives Saved',
    'about.impact.service': 'Emergency Service',
    'about.values': 'Our Values',
    'about.trust': 'Trust',
    'about.trust.text': 'Building trust through transparency and reliability',
    'about.compassion': 'Compassion',
    'about.compassion.text': 'Driven by empathy and care for human life',
    'about.community': 'Community',
    'about.community.text': 'Building stronger communities through collaboration',
    'about.excellence': 'Excellence',
    'about.excellence.text': 'Committed to the highest standards of service',
    'about.join': 'Join Our Mission',
    'about.join.text': 'Be part of our life-saving network. Whether you want to donate blood or need emergency assistance, we\'re here to help connect you with the right people.',
    'about.contact': 'Contact Us',
    
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch with Tamil Nadu Blood Foundation. We\'re here to help with your blood donation needs.',
    'contact.getintouch': 'Get In Touch',
    'contact.emergency.helpline': 'Emergency Helpline',
    'contact.emergency.desc': 'Available 24/7 for blood emergencies',
    'contact.general': 'General Helpline',
    'contact.hours': 'Mon - Fri, 9:00 AM - 6:00 PM',
    'contact.email': 'Email',
    'contact.address': 'Address',
    'contact.office.hours': 'Office Hours',
    'contact.monday': 'Monday - Friday: 9:00 AM - 6:00 PM',
    'contact.saturday': 'Saturday: 9:00 AM - 1:00 PM',
    'contact.sunday': 'Sunday: Closed',
    'contact.emergency.247': 'Emergency service available 24/7',
    'contact.coordinators': 'District Coordinators',
    'contact.coordinators.desc': 'For district-specific queries, contact your local coordinator:',
    'contact.coordinators.more': 'More district coordinators available on request',
    'contact.form': 'Send us a Message',
    'contact.name': 'Full Name',
    'contact.name.placeholder': 'Enter your full name',
    'contact.email.placeholder': 'Enter your email',
    'contact.subject': 'Subject',
    'contact.subject.placeholder': 'What is this regarding?',
    'contact.message': 'Message',
    'contact.message.placeholder': 'Please provide details about your inquiry...',
    'contact.send': 'Send Message',
    'contact.faq': 'Frequently Asked Questions',
    'contact.faq1.q': 'How can I register as a blood donor?',
    'contact.faq1.a': 'Visit our "Join as Donor" page and fill out the registration form with your details.',
    'contact.faq2.q': 'Is there a cost for using this service?',
    'contact.faq2.a': 'Our blood donor connection service is completely free for both donors and recipients.',
    'contact.faq3.q': 'How quickly can I find a donor in an emergency?',
    'contact.faq3.a': 'Our emergency service operates 24/7. Call 1962 for immediate assistance.',
    
    // Join Donor Page
    'join.title': 'Join as Blood Donor',
    'join.subtitle': 'Become a life-saver by registering as a blood donor. Your single donation can save up to three lives.',
    'join.eligibility': 'Eligibility Requirements',
    'join.req1': 'Age between 18-65 years',
    'join.req2': 'Minimum weight of 50kg',
    'join.req3': 'Good general health',
    'join.req4': 'No history of hepatitis, HIV, or other blood-borne diseases',
    'join.req5': 'No major surgery in the last 6 months',
    'join.req6': 'Not pregnant or breastfeeding',
    'join.req7': 'No recent tattoos or piercings (within 6 months)',
    'join.benefits': 'Benefits of Donating',
    'join.benefit1': 'Save up to 3 lives with one donation',
    'join.benefit2': 'Free health check-up before donation',
    'join.benefit3': 'Reduces risk of heart disease',
    'join.benefit4': 'Helps maintain healthy iron levels',
    'join.benefit5': 'Free blood group testing',
    'join.note': 'Important Note',
    'join.note.text': 'Donation is safe and voluntary. You can donate blood every 3 months. Our medical team will conduct a health screening before each donation.',
    'join.form': 'Donor Registration Form',
    'join.personal': 'Personal Information',
    'join.fullname': 'Full Name',
    'join.age': 'Age',
    'join.gender': 'Gender',
    'join.gender.select': 'Select Gender',
    'join.gender.male': 'Male',
    'join.gender.female': 'Female',
    'join.gender.other': 'Other',
    'join.bloodgroup.select': 'Select Blood Group',
    'join.location': 'Location Information',
    'join.district.select': 'Select District',
    'join.contact.info': 'Contact Information',
    'join.mobile': 'Mobile Number',
    'join.alternate': 'Alternate Number',
    'join.medical': 'Medical Information',
    'join.lastdonated': 'Last Donated Date (if applicable)',
    'join.conditions': 'Medical Conditions (if any)',
    'join.conditions.placeholder': 'Please mention any medical conditions, medications, or allergies...',
    'join.terms': 'Terms and Conditions',
    'join.terms.text': 'I hereby declare that the information provided is true and accurate. I understand that blood donation is voluntary and I consent to be contacted for blood donation emergencies. I agree to maintain my availability status and follow the donation guidelines provided by Tamil Nadu Blood Foundation.',
    'join.submit': 'Register as Blood Donor',
    
    // Emergency Page
    'emerg.title': 'Emergency Blood Requests',
    'emerg.subtitle': '24/7 Emergency Blood Donor Network - Every Second Counts',
    'emerg.helpline': 'Emergency Helpline: 1962',
    'emerg.post': 'Post Emergency Request',
    'emerg.patient': 'Patient Information',
    'emerg.patient.name': 'Patient Name',
    'emerg.patient.placeholder': 'Enter patient\'s name',
    'emerg.bloodgroup.req': 'Blood Group Required',
    'emerg.units': 'Units Needed',
    'emerg.units.placeholder': 'Number of units',
    'emerg.urgency': 'Urgency Level',
    'emerg.urgency.high': 'High - Immediate (within 2 hours)',
    'emerg.urgency.medium': 'Medium - Urgent (within 6 hours)',
    'emerg.urgency.low': 'Low - Planned (within 24 hours)',
    'emerg.hospital': 'Hospital Information',
    'emerg.hospital.name': 'Hospital Name',
    'emerg.hospital.placeholder': 'Enter hospital name',
    'emerg.hospital.location': 'Hospital Location',
    'emerg.hospital.location.placeholder': 'Hospital address/location',
    'emerg.contact.info': 'Contact Information',
    'emerg.contact.number': 'Contact Number',
    'emerg.additional': 'Additional Information',
    'emerg.additional.placeholder': 'Any additional information (medical condition, preferred time for donation, etc.)',
    'emerg.submit': 'Post Emergency Request',
    'emerg.current': 'Current Emergency Requests',
    'emerg.high': 'High',
    'emerg.medium': 'Medium',
    'emerg.low': 'Low',
    'emerg.patient.label': 'Patient:',
    'emerg.guidelines': 'Emergency Guidelines',
    'emerg.guide1': 'Verify blood group compatibility before donation',
    'emerg.guide2': 'Contact hospital directly for urgent requirements',
    'emerg.guide3': 'Donors should carry valid ID and health certificate',
    'emerg.guide4': 'Report fake or fraudulent requests immediately',
    'emerg.guide5': 'Emergency helpline available 24/7: 1962',
    
    // Facilities Page
    'facilities.title': 'Blood Bank Facilities',
    'facilities.subtitle': 'Government blood banks, emergency helplines, and upcoming donation camps across Tamil Nadu',
    'facilities.emergency.title': 'Emergency Helplines',
    'facilities.bloodbank': 'State Blood Bank Helpline',
    'facilities.bloodbank.desc': '24/7 emergency blood requirements',
    'facilities.ambulance': 'Ambulance Service',
    'facilities.ambulance.desc': 'Emergency medical transportation',
    'facilities.health': 'Health Department Helpline',
    'facilities.health.desc': 'Medical emergencies and guidance',
    'facilities.call': 'Call Now',
    'facilities.govt.title': 'Government Blood Banks',
    'facilities.govt.subtitle': 'Major government blood banks across Tamil Nadu districts',
    'facilities.govt': 'Government',
    'facilities.operating': 'Operating Hours:',
    'facilities.services': 'Services:',
    'facilities.directions': 'Directions',
    'facilities.camps.title': 'Upcoming Blood Donation Camps',
    'facilities.camps.subtitle': 'Join our organized blood donation drives across Tamil Nadu',
    'facilities.upcoming': 'Upcoming',
    'facilities.organized': 'Organized by:',
    'facilities.expected': 'Expected Donors:',
    'facilities.register': 'Register for Camp',
    'facilities.location': 'Location',
    'facilities.organize': 'Want to Organize a Blood Donation Camp?',
    'facilities.requirements': 'Requirements:',
    'facilities.req1': 'Minimum 50 expected donors',
    'facilities.req2': 'Proper venue with adequate space',
    'facilities.req3': 'Medical staff coordination',
    'facilities.req4': 'Advance booking (minimum 2 weeks)',
    'facilities.req5': 'Necessary permits and approvals',
    'facilities.provide': 'We Provide:',
    'facilities.prov1': 'Trained medical staff',
    'facilities.prov2': 'All medical equipment',
    'facilities.prov3': 'Blood collection bags',
    'facilities.prov4': 'Safety and hygiene supplies',
    'facilities.prov5': 'Certificates for donors',
    'facilities.organize.btn': 'Contact Us to Organize a Camp',
  },
  ta: {
    // Header  
    'site.title': 'தமிழ்நாடு இரத்த வங்கி அறக்கட்டளை',
    'site.subtitle': 'உயிர்களை காப்போம்',
    'emergency.hotline': 'அவசரம்: 1962',
    
    // Navigation
    'nav.home': 'முகப்பு',
    'nav.about': 'எங்களைப் பற்றி',
    'nav.contact': 'தொடர்பு',
    'nav.facilities': 'வசதிகள்',
    'nav.join': 'தானாளராக சேர',
    'nav.emergency': 'அவசர கோரிக்கைகள்',
    
    // Home Page
    'hero.title': 'இரத்த தானம் மூலம் உயிர்களை காப்பீர்கள்',
    'hero.subtitle': 'தமிழ்நாட்டின் 38 மாவட்டங்களில் உள்ள தேவையுள்ளவர்களுடன் தானாளர்களை இணைக்கும்',
    'stats.donors': 'செயலில் உள்ள தானாளர்கள்',
    'stats.districts': 'மாவட்டங்கள் சேர்க்கப்பட்டது',
    'stats.service': 'அவசர சேவை',
    'cta.donate': 'தானாளராக ஆகுங்கள்',
    'cta.emergency': 'அவசர கோரிக்கை',
    
    // Emergency Section
    'emergency.urgent': 'அவசர இரத்த கோரிக்கைகள்',
    'emergency.needed': 'தேவை',
    'emergency.contact': 'தொடர்பு:',
    
    // Search Section
    'search.title': 'இரத்த தானாளர்களை கண்டறியவும்',
    'search.subtitle': 'உங்கள் அருகிலுள்ள தானாளர்களை கண்டறிய மாவட்டம் மற்றும் இரத்த வகையை தேடவும்',
    'search.district': 'மாவட்டம் தேடவும்',
    'search.district.placeholder': 'மாவட்ட பெயரை உள்ளிடவும்...',
    'search.bloodgroup': 'இரத்த வகை (விருப்பம்)',
    'search.bloodgroup.all': 'அனைத்து இரத்த வகைகள்',
    'search.button': 'தானாளர்களை தேடவும்',
    
    // Districts
    'districts.title': 'மாவட்டம் வாரியாக பார்வையிடவும்',
    'districts.subtitle': 'உங்கள் பகுதியில் உள்ள இரத்த தானாளர்களை கண்டறிய உங்கள் மாவட்டத்தை தேர்ந்தெடுக்கவும்',
    'districts.find': 'தானாளர்களை கண்டறியவும்',
    'districts.none': 'பொருந்தும் மாவட்டங்கள் இல்லை',
    
    // Blood Group Selection
    'bloodgroup.title': 'இரத்த தானாளர்கள்',
    'bloodgroup.subtitle': 'உங்களுக்கு தேவையான இரத்த வகையை தேர்ந்தெடுக்கவும்',
    'bloodgroup.back': 'மாவட்டங்களுக்கு திரும்பு',
    'bloodgroup.type': 'இரத்த வகை',
    'bloodgroup.compatibility': 'இரத்த இணக்கத்தன்மை',
    'bloodgroup.universal.donor': 'உலகளாவிய தானாளர்:',
    'bloodgroup.universal.recipient': 'உலகளாவிய பெறுநர்:',
    'bloodgroup.verify': 'நினைவில் கொள்ளுங்கள்: இரத்த பரிமாற்றத்திற்கு முன் எப்போதும் மருத்துவ நிபுணர்களுடன் இணக்கத்தன்மையை சரிபார்க்கவும்.',
    'bloodgroup.guidelines': 'தானம் வழிகாட்டுதல்கள்',
    'bloodgroup.gap': 'தானங்களுக்கு இடையில் குறைந்தபட்சம் 3 மாத இடைவெளி',
    'bloodgroup.age': 'வயது: 18-65 ஆண்டுகள்',
    'bloodgroup.weight': 'எடை: குறைந்தது 50 கிலோ',
    'bloodgroup.health': 'நல்ல உடல்நலம் தேவை',
    
    // Donor List
    'donorlist.title': 'தானாளர்கள்',
    'donorlist.found': 'தானாளர்கள் கிடைத்தன',
    'donorlist.back': 'இரத்த வகைகளுக்கு திரும்பு',
    'donorlist.name': 'பெயர்',
    'donorlist.age': 'வயது',
    'donorlist.bloodgroup': 'இரத்த வகை',
    'donorlist.lastdonated': 'கடைசி தானம்',
    'donorlist.status': 'நிலை',
    'donorlist.contact': 'தொடர்பு',
    'donorlist.years': 'வயது',
    'donorlist.available': 'கிடைக்கும்',
    'donorlist.notavailable': 'கிடைக்காது',
    'donorlist.recent': 'சமீபத்தில் தானம் செய்தவர்',
    'donorlist.call': 'அழைக்க',
    'donorlist.whatsapp': 'வாட்ஸ்அப்',
    'donorlist.none': 'தானாளர்கள் இல்லை',
    'donorlist.none.desc': 'எங்களால் கண்டுபிடிக்க முடியவில்லை',
    'donorlist.none.desc2': 'தானாளர்கள்',
    'donorlist.none.desc3': 'தற்போது.',
    'donorlist.register': 'தானாளராக பதிவு செய்யவும்',
    'donorlist.emergency': 'அவசர கோரிக்கையை இடுகையிடவும்',
    
    // About Page
    'about.title': 'தமிழ்நாடு இரத்த வங்கி அறக்கட்டளை பற்றி',
    'about.subtitle': 'தமிழ்நாடு முழுவதும் உதவியுள்ள இரத்த தானாளர்களுக்கும் அவசர தேவையுள்ளவர்களுக்கும் இடையிலான இடைவெளியைக் குறைத்தல்',
    'about.mission': 'எங்கள் நோக்கம்',
    'about.mission.text': 'தமிழ்நாட்டின் அனைத்து 38 மாவட்டங்களிலும் தேவைப்படும் நோயாளிகளுடன் இரத்த தானாளர்களை இணைக்கும் வலுவான நெட்வொர்க்கை உருவாக்குவது. திறமையான, அணுகக்கூடிய மற்றும் நம்பகமான இரத்த தான அமைப்பை பராமரிப்பதன் மூலம் இரத்த கிடைக்காமையால் எந்த உயிரும் இழக்கப்படாமல் இருப்பதை உறுதி செய்ய நாங்கள் முயற்சிக்கிறோம்.',
    'about.vision': 'எங்கள் பார்வை',
    'about.vision.text': 'தமிழ்நாட்டின் மிகவும் நம்பகமான இரத்த தான தளமாக மாறுவது, ஒவ்வொரு குடிமகனும் தேவைப்படும் போது பாதுகாப்பான இரத்தத்தை எளிதில் அணுக முடியும், மற்றும் ஒவ்வொரு விருப்பமுள்ள தானாளரும் தங்கள் சமூகத்திலும் அதற்கு அப்பாலும் உயிர்களைக் காப்பாற்ற பங்களிக்க முடியும்.',
    'about.what': 'நாம் என்ன செய்கிறோம்',
    'about.what.subtitle': 'எங்கள் விரிவான தளம் தானாளர்களை பெறுநர்களுடன் இணைத்து அத்தியாவசிய சேவைகளை வழங்குகிறது',
    'about.donor.reg': 'தானாளர் பதிவு',
    'about.donor.reg.text': 'தமிழ்நாட்டின் அனைத்து மாவட்டங்களிலும் விருப்பமுள்ள இரத்த தானாளர்களுக்கான எளிதான பதிவு செயல்முறை',
    'about.emergency.resp': 'அவசர பதில்',
    'about.emergency.resp.text': '24/7 அவசர இரத்த கோரிக்கை அமைப்பு நோயாளிகளை கிடைக்கும் தானாளர்களுடன் உடனடியாக இணைக்கிறது',
    'about.district.cov': 'மாவட்ட கவரேஜ்',
    'about.district.cov.text': 'உள்ளூர் தானாளர் நெட்வொர்க்குகளுடன் அனைத்து 38 தமிழ்நாடு மாவட்டங்களின் முழுமையான கவரேஜ்',
    'about.impact': 'எங்கள் தாக்கம்',
    'about.impact.subtitle': 'தமிழ்நாடு முழுவதும் வேறுபாட்டை உருவாக்குதல்',
    'about.impact.donors': 'பதிவு செய்யப்பட்ட தானாளர்கள்',
    'about.impact.districts': 'மாவட்டங்கள் சேர்க்கப்பட்டன',
    'about.impact.lives': 'உயிர்கள் காப்பாற்றப்பட்டன',
    'about.impact.service': 'அவசர சேவை',
    'about.values': 'எங்கள் மதிப்புகள்',
    'about.trust': 'நம்பிக்கை',
    'about.trust.text': 'வெளிப்படைத்தன்மை மற்றும் நம்பகத்தன்மை மூலம் நம்பிக்கையை கட்டியெழுப்புதல்',
    'about.compassion': 'இரக்கம்',
    'about.compassion.text': 'மனித வாழ்க்கைக்கான பச்சாதாபம் மற்றும் அக்கறையால் இயக்கப்படுகிறது',
    'about.community': 'சமூகம்',
    'about.community.text': 'ஒத்துழைப்பு மூலம் வலுவான சமூகங்களை உருவாக்குதல்',
    'about.excellence': 'சிறப்பு',
    'about.excellence.text': 'உயர்ந்த தரமான சேவைக்கு அர்ப்பணிப்பு',
    'about.join': 'எங்கள் நோக்கத்தில் சேருங்கள்',
    'about.join.text': 'எங்கள் உயிர்காக்கும் நெட்வொர்க்கின் ஒரு பகுதியாக இருங்கள். நீங்கள் இரத்தம் தானம் செய்ய விரும்பினாலும் அல்லது அவசர உதவி தேவைப்பட்டாலும், சரியான நபர்களுடன் உங்களை இணைக்க நாங்கள் இங்கே இருக்கிறோம்.',
    'about.contact': 'எங்களை தொடர்பு கொள்ளுங்கள்',
    
    // Contact Page
    'contact.title': 'எங்களை தொடர்பு கொள்ளுங்கள்',
    'contact.subtitle': 'தமிழ்நாடு இரத்த வங்கி அறக்கட்டளையுடன் தொடர்பு கொள்ளுங்கள். உங்கள் இரத்த தான தேவைகளுக்கு உதவ நாங்கள் இங்கே இருக்கிறோம்.',
    'contact.getintouch': 'தொடர்பில் இருங்கள்',
    'contact.emergency.helpline': 'அவசர ஹெல்ப்லைன்',
    'contact.emergency.desc': 'இரத்த அவசரநிலைகளுக்கு 24/7 கிடைக்கும்',
    'contact.general': 'பொது ஹெல்ப்லைன்',
    'contact.hours': 'திங்கள் - வெள்ளி, காலை 9:00 - மாலை 6:00',
    'contact.email': 'மின்னஞ்சல்',
    'contact.address': 'முகவரி',
    'contact.office.hours': 'அலுவலக நேரங்கள்',
    'contact.monday': 'திங்கள் - வெள்ளி: காலை 9:00 - மாலை 6:00',
    'contact.saturday': 'சனி: காலை 9:00 - பிற்பகல் 1:00',
    'contact.sunday': 'ஞாயிறு: மூடப்பட்டது',
    'contact.emergency.247': 'அவசர சேவை 24/7 கிடைக்கும்',
    'contact.coordinators': 'மாவட்ட ஒருங்கிணைப்பாளர்கள்',
    'contact.coordinators.desc': 'மாவட்ட-குறிப்பிட்ட கேள்விகளுக்கு, உங்கள் உள்ளூர் ஒருங்கிணைப்பாளரை தொடர்பு கொள்ளவும்:',
    'contact.coordinators.more': 'கோரிக்கையின் பேரில் மேலும் மாவட்ட ஒருங்கிணைப்பாளர்கள் கிடைக்கின்றனர்',
    'contact.form': 'எங்களுக்கு செய்தி அனுப்பவும்',
    'contact.name': 'முழு பெயர்',
    'contact.name.placeholder': 'உங்கள் முழு பெயரை உள்ளிடவும்',
    'contact.email.placeholder': 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
    'contact.subject': 'பொருள்',
    'contact.subject.placeholder': 'இது எதைப் பற்றியது?',
    'contact.message': 'செய்தி',
    'contact.message.placeholder': 'உங்கள் விசாரணை பற்றிய விவரங்களை வழங்கவும்...',
    'contact.send': 'செய்தி அனுப்பு',
    'contact.faq': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    'contact.faq1.q': 'நான் எப்படி இரத்த தானாளராக பதிவு செய்யலாம்?',
    'contact.faq1.a': 'எங்கள் "தானாளராக சேர" பக்கத்தை பார்வையிட்டு உங்கள் விவரங்களுடன் பதிவு படிவத்தை பூர்த்தி செய்யவும்.',
    'contact.faq2.q': 'இந்த சேவையைப் பயன்படுத்த கட்டணம் உள்ளதா?',
    'contact.faq2.a': 'எங்கள் இரத்த தானாளர் இணைப்பு சேவை தானாளர்கள் மற்றும் பெறுநர்கள் இருவருக்கும் முற்றிலும் இலவசம்.',
    'contact.faq3.q': 'அவசரநிலையில் எவ்வளவு விரைவாக தானாளரை கண்டுபிடிக்க முடியும்?',
    'contact.faq3.a': 'எங்கள் அவசர சேவை 24/7 செயல்படுகிறது. உடனடி உதவிக்கு 1962 ஐ அழைக்கவும்.',
    
    // Join Donor Page
    'join.title': 'இரத்த தானாளராக சேருங்கள்',
    'join.subtitle': 'இரத்த தானாளராக பதிவு செய்வதன் மூலம் உயிர்காப்பவராக மாறுங்கள். உங்கள் ஒற்றை தானம் மூன்று உயிர்களைக் காப்பாற்ற முடியும்.',
    'join.eligibility': 'தகுதி தேவைகள்',
    'join.req1': 'வயது 18-65 ஆண்டுகளுக்கு இடையில்',
    'join.req2': 'குறைந்தபட்ச எடை 50 கிலோ',
    'join.req3': 'நல்ல பொது ஆரோக்கியம்',
    'join.req4': 'ஹெபடைடிஸ், எச்.ஐ.வி அல்லது பிற இரத்த-பரவும் நோய்களின் வரலாறு இல்லை',
    'join.req5': 'கடந்த 6 மாதங்களில் பெரிய அறுவை சிகிச்சை இல்லை',
    'join.req6': 'கர்ப்பமாக இல்லை அல்லது தாய்ப்பால் கொடுக்கவில்லை',
    'join.req7': 'சமீபத்திய பச்சை குத்தல்கள் அல்லது துளையிடல் இல்லை (6 மாதங்களுக்குள்)',
    'join.benefits': 'தானம் செய்வதன் நன்மைகள்',
    'join.benefit1': 'ஒரு தானத்தில் 3 உயிர்களைக் காப்பாற்றவும்',
    'join.benefit2': 'தானத்திற்கு முன் இலவச உடல்நல பரிசோதனை',
    'join.benefit3': 'இதய நோய் அபாயத்தை குறைக்கிறது',
    'join.benefit4': 'ஆரோக்கியமான இரும்பு அளவைப் பராமரிக்க உதவுகிறது',
    'join.benefit5': 'இலவச இரத்த வகை சோதனை',
    'join.note': 'முக்கியக் குறிப்பு',
    'join.note.text': 'தானம் பாதுகாப்பானது மற்றும் தன்னார்வமானது. நீங்கள் ஒவ்வொரு 3 மாதங்களுக்கும் இரத்தம் தானம் செய்யலாம். ஒவ்வொரு தானத்திற்கு முன்பும் எங்கள் மருத்துவ குழு உடல்நல பரிசோதனை நடத்தும்.',
    'join.form': 'தானாளர் பதிவு படிவம்',
    'join.personal': 'தனிப்பட்ட தகவல்',
    'join.fullname': 'முழு பெயர்',
    'join.age': 'வயது',
    'join.gender': 'பாலினம்',
    'join.gender.select': 'பாலினத்தை தேர்ந்தெடுக்கவும்',
    'join.gender.male': 'ஆண்',
    'join.gender.female': 'பெண்',
    'join.gender.other': 'மற்றவை',
    'join.bloodgroup.select': 'இரத்த வகையை தேர்ந்தெடுக்கவும்',
    'join.location': 'இருப்பிட தகவல்',
    'join.district.select': 'மாவட்டத்தை தேர்ந்தெடுக்கவும்',
    'join.contact.info': 'தொடர்பு தகவல்',
    'join.mobile': 'மொபைல் எண்',
    'join.alternate': 'மாற்று எண்',
    'join.medical': 'மருத்துவ தகவல்',
    'join.lastdonated': 'கடைசி தானம் செய்த தேதி (பொருந்தினால்)',
    'join.conditions': 'மருத்துவ நிலைமைகள் (ஏதேனும் இருந்தால்)',
    'join.conditions.placeholder': 'எந்த மருத்துவ நிலைகள், மருந்துகள் அல்லது ஒவ்வாமைகளையும் குறிப்பிடவும்...',
    'join.terms': 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
    'join.terms.text': 'வழங்கப்பட்ட தகவல் உண்மை மற்றும் துல்லியமானது என்று நான் இதன்மூலம் அறிவிக்கிறேன். இரத்த தானம் தன்னார்வமானது என்பதை நான் புரிந்துகொள்கிறேன் மற்றும் இரத்த தான அவசரநிலைகளுக்காக தொடர்பு கொள்ள நான் சம்மதிக்கிறேன். எனது கிடைக்கும் நிலையைப் பராமரிக்கவும் தமிழ்நாடு இரத்த வங்கி அறக்கட்டளையால் வழங்கப்பட்ட தான வழிகாட்டுதல்களைப் பின்பற்றவும் நான் ஒப்புக்கொள்கிறேன்.',
    'join.submit': 'இரத்த தானாளராக பதிவு செய்யவும்',
    
    // Emergency Page
    'emerg.title': 'அவசர இரத்த கோரிக்கைகள்',
    'emerg.subtitle': '24/7 அவசர இரத்த தானாளர் நெட்வொர்க் - ஒவ்வொரு வினாடியும் எண்ணப்படுகிறது',
    'emerg.helpline': 'அவசர ஹெல்ப்லைன்: 1962',
    'emerg.post': 'அவசர கோரிக்கையை இடுகையிடவும்',
    'emerg.patient': 'நோயாளி தகவல்',
    'emerg.patient.name': 'நோயாளி பெயர்',
    'emerg.patient.placeholder': 'நோயாளியின் பெயரை உள்ளிடவும்',
    'emerg.bloodgroup.req': 'தேவையான இரத்த வகை',
    'emerg.units': 'தேவையான யூனிட்கள்',
    'emerg.units.placeholder': 'யூனிட்களின் எண்ணிக்கை',
    'emerg.urgency': 'அவசர நிலை',
    'emerg.urgency.high': 'உயர் - உடனடி (2 மணி நேரத்திற்குள்)',
    'emerg.urgency.medium': 'நடுத்தர - அவசரம் (6 மணி நேரத்திற்குள்)',
    'emerg.urgency.low': 'குறைவு - திட்டமிடப்பட்ட (24 மணி நேரத்திற்குள்)',
    'emerg.hospital': 'மருத்துவமனை தகவல்',
    'emerg.hospital.name': 'மருத்துவமனை பெயர்',
    'emerg.hospital.placeholder': 'மருத்துவமனை பெயரை உள்ளிடவும்',
    'emerg.hospital.location': 'மருத்துவமனை இருப்பிடம்',
    'emerg.hospital.location.placeholder': 'மருத்துவமனை முகவரி/இருப்பிடம்',
    'emerg.contact.info': 'தொடர்பு தகவல்',
    'emerg.contact.number': 'தொடர்பு எண்',
    'emerg.additional': 'கூடுதல் தகவல்',
    'emerg.additional.placeholder': 'எந்த கூடுதல் தகவலும் (மருத்துவ நிலை, விரும்பப்படும் தான நேரம், போன்றவை)',
    'emerg.submit': 'அவசர கோரிக்கையை இடுகையிடவும்',
    'emerg.current': 'தற்போதைய அவசர கோரிக்கைகள்',
    'emerg.high': 'உயர்',
    'emerg.medium': 'நடுத்தர',
    'emerg.low': 'குறைவு',
    'emerg.patient.label': 'நோயாளி:',
    'emerg.guidelines': 'அவசர வழிகாட்டுதல்கள்',
    'emerg.guide1': 'தானத்திற்கு முன் இரத்த வகை இணக்கத்தன்மையை சரிபார்க்கவும்',
    'emerg.guide2': 'அவசர தேவைகளுக்கு நேரடியாக மருத்துவமனையை தொடர்பு கொள்ளவும்',
    'emerg.guide3': 'தானாளர்கள் செல்லுபடியாகும் அடையாள அட்டை மற்றும் உடல்நல சான்றிதழை எடுத்துச் செல்ல வேண்டும்',
    'emerg.guide4': 'போலி அல்லது மோசடியான கோரிக்கைகளை உடனடியாக தெரிவிக்கவும்',
    'emerg.guide5': 'அவசர ஹெல்ப்லைன் 24/7 கிடைக்கும்: 1962',
    
    // Facilities Page
    'facilities.title': 'இரத்த வங்கி வசதிகள்',
    'facilities.subtitle': 'தமிழ்நாடு முழுவதும் அரசு இரத்த வங்கிகள், அவசர ஹெல்ப்லைன்கள் மற்றும் வரவிருக்கும் தான முகாம்கள்',
    'facilities.emergency.title': 'அவசர ஹெல்ப்லைன்கள்',
    'facilities.bloodbank': 'மாநில இரத்த வங்கி ஹெல்ப்லைன்',
    'facilities.bloodbank.desc': '24/7 அவசர இரத்த தேவைகள்',
    'facilities.ambulance': 'ஆம்புலன்ஸ் சேவை',
    'facilities.ambulance.desc': 'அவசர மருத்துவ போக்குவரத்து',
    'facilities.health': 'சுகாதார துறை ஹெல்ப்லைன்',
    'facilities.health.desc': 'மருத்துவ அவசரநிலைகள் மற்றும் வழிகாட்டுதல்',
    'facilities.call': 'இப்போது அழைக்கவும்',
    'facilities.govt.title': 'அரசு இரத்த வங்கிகள்',
    'facilities.govt.subtitle': 'தமிழ்நாடு மாவட்டங்களில் உள்ள முக்கிய அரசு இரத்த வங்கிகள்',
    'facilities.govt': 'அரசு',
    'facilities.operating': 'இயக்க நேரங்கள்:',
    'facilities.services': 'சேவைகள்:',
    'facilities.directions': 'திசைகள்',
    'facilities.camps.title': 'வரவிருக்கும் இரத்த தான முகாம்கள்',
    'facilities.camps.subtitle': 'தமிழ்நாடு முழுவதும் எங்கள் ஒழுங்கமைக்கப்பட்ட இரத்த தான பிரச்சாரங்களில் சேருங்கள்',
    'facilities.upcoming': 'வரவிருக்கும்',
    'facilities.organized': 'ஏற்பாடு செய்தவர்:',
    'facilities.expected': 'எதிர்பார்க்கப்படும் தானாளர்கள்:',
    'facilities.register': 'முகாமுக்கு பதிவு செய்யவும்',
    'facilities.location': 'இருப்பிடம்',
    'facilities.organize': 'இரத்த தான முகாமை ஏற்பாடு செய்ய விரும்புகிறீர்களா?',
    'facilities.requirements': 'தேவைகள்:',
    'facilities.req1': 'குறைந்தபட்சம் 50 எதிர்பார்க்கப்படும் தானாளர்கள்',
    'facilities.req2': 'போதுமான இடத்துடன் சரியான இடம்',
    'facilities.req3': 'மருத்துவ பணியாளர் ஒருங்கிணைப்பு',
    'facilities.req4': 'முன் பதிவு (குறைந்தது 2 வாரங்கள்)',
    'facilities.req5': 'தேவையான அனுமதிகள் மற்றும் ஒப்புதல்கள்',
    'facilities.provide': 'நாங்கள் வழங்குவது:',
    'facilities.prov1': 'பயிற்சி பெற்ற மருத்துவ பணியாளர்கள்',
    'facilities.prov2': 'அனைத்து மருத்துவ உபகரணங்கள்',
    'facilities.prov3': 'இரத்த சேகரிப்பு பைகள்',
    'facilities.prov4': 'பாதுகாப்பு மற்றும் சுகாதார பொருட்கள்',
    'facilities.prov5': 'தானாளர்களுக்கான சான்றிதழ்கள்',
    'facilities.organize.btn': 'முகாமை ஏற்பாடு செய்ய எங்களை தொடர்பு கொள்ளுங்கள்',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ta' : 'en');
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};